#-*-coding:utf-8-*-
print "                      只要彼此爱过一次                          "
print "如果不曾相逢"
print "也许心绪永远不会沉重"
print "如果真的失之交臂"
print "恐怕一生也不得轻松"
print "一个眼神便足以让心海掠过飓风"
print "在贫瘠的土地上"
print "更深地懂得风景"
print "一次远行便足以憔悴了一颗羸弱的心"
print "每望一眼秋水微澜"
print "便恨不得泪水盈盈"
print "死怎能不从容不迫"
print "爱又怎能无动于衷"
print "只要彼此爱过一次"
print "就是无憾的人生"
